### PR TITLE
Add support for Nextcloud News v15

### PR DESCRIPTION
**Pull request by DriverXX**
This adds support for Nextcloud news v15 but only in cli mode (not in the web mode).
At the moment you need to set `apilevel = v15` to work with the new API.

Actually, I don't like that much the idea of using the version of the APP to identify the version of the API; any suggestion?

### CODE REVIEW

**Comment by guddl** [comment]
Hi @DriverXX.

thanks for the patch. I applied it to an existing installation - changend the apilevel to v15 

But when I start the news-updater I get the following error:

>sudo -u www-data nextcloud-news-updater --loglevel info -c /etc/nextcloud/news/updater.ini 
2020-10-09 20:40:08,478 - Nextcloud News Updater - INFO - Running update in an interval of 900 seconds using 10 threads
2020-10-09 20:40:08,478 - Nextcloud News Updater - INFO - Running before update command: /usr/bin/php -f /var/www/nextcloud/occ news:updater:before-update
2020-10-09 20:40:08,965 - Nextcloud News Updater - ERROR - info() takes 2 positional arguments but 3 were given: Trying again in 30 seconds
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/nextcloud_news_updater/api/updater.py", line 70, in run
    feeds = self.all_feeds()
  File "/usr/local/lib/python3.8/dist-packages/nextcloud_news_updater/api/cli.py", line 131, in all_feeds
    self.logger.info("Running get user list command: %s",
TypeError: info() takes 2 positional arguments but 3 were given

Do you have any tips for me?

Cheers,
Andreas

**Comment by DriverXX** [comment]
Hi @guddl,
Thanks, it should work now

**Comment by guddl** [comment]
> Hi @guddl,
> Thanks, it should work now

Perfect 🥇

**Comment by BernhardPosselt** [comment]
Can you check if the current version works, then I'll push an update to the registry

**Comment by guddl** [comment]
Works for me :-)

**Comment by z3ntu** [comment]
Can't the api level be auto-detected somehow? Making all users have to change the config is non-optimal in my opinion.

But publishing this version is still better than having no compatible release; but I think most users will just notice their feeds not updating (as was the case with my instance) and having to dig around why the updater doesn't work anymore.

**Pull request merged**
